### ISSUE TITLE
Autocomplete remove whitespace

### ISSUE THREAD

**Issue by barraIhsan** [ImUrX/vscode-scarpet#18]
When you have whitespace before the autocomplete, then it will delete those whitespace, its really annoying, because I have to tidy my code again
https://user-images.githubusercontent.com/57800056/109741632-045d4e00-7c00-11eb-804c-67664ef27254.mp4

**Comment by ImUrX** [comment]
this is actually from vscode, but maybe im wrong.

edit: like it knows if you should be in an indented space. will check what i can do

**Comment by ImUrX** [comment]
fixed on b48e955
