### ISSUE TITLE
Closing parenthesis in string ends string

### ISSUE THREAD

**Issue by Tre5et** [ImUrX/vscode-scarpet#20]
Having a closing parenthesis in a string acts like having an apostrophe and therefore inverts all future strings (see screenshots).

![Screenshot 2021-04-25 103345](https://user-images.githubusercontent.com/79938957/115986727-ec77ca00-a5b1-11eb-8ad7-1960fadddf92.png)
![Screenshot 2021-04-25 103314](https://user-images.githubusercontent.com/79938957/115986733-eeda2400-a5b1-11eb-8b80-9813cb8598b4.png)

**Comment by ImUrX** [comment]
Will fix it when I can

**Comment by ImUrX** [comment]
It's been fixed, do check though
