### ISSUE TITLE
[Bug][Low pri] When changing language in a .sc file then putting scarpet again, plugin only half works

### ISSUE THREAD

**Issue by Ghoulboy78** [ImUrX/vscode-scarpet#3]
Basically, if you open a .sc file, it will work, but if you change language to, say, python, it works, and the when you revert to scarpet, it won't work even though you are in a .sc file.
And if you open a new file .txt, and change the lang to scarpet in the bottom right corner, thatn it wont work. It will highlight properly, but no autocompletion (this isnt a biggie, which is why there is low pri on the bug name)

**Comment by ImUrX** [comment]
It may or may not be related to the registering of the completion provider, will check it out

**Comment by ImUrX** [comment]
Can you check on the new release?

**Comment by Ghoulboy78** [comment]
is fixed in 0.1.5!
