### ISSUE TITLE
add icon for scarpet files

### ISSUE THREAD

**Issue by ImUrX** [ImUrX/vscode-scarpet#4]
I need opinions on this matter, the current icon that gnembon got me is 
![scarpet icon](https://repository-images.githubusercontent.com/180248343/8315d280-6bcb-11ea-9028-425d5a89cd0d) 
but its not made for a file icon in vscode. 

My current idea was this one 
![svg icon](https://i.fiery.me/Ibdng.svg) 
(its an svg you can download it and edit it) 
based on the idea of a >_ with a carpet, but well 

anyone got any other idea?

**Comment by ImUrX** [comment]
Another proposed design by a friend is something like this ![polar](https://cdn.discordapp.com/attachments/540181360476684306/691505110370615466/Screenshot_20200323_173413.png)

**Comment by ImUrX** [comment]
![polar 2 what a genius](https://cdn.discordapp.com/attachments/540181360476684306/691506983970537522/Screenshot_20200323_174138.png)

**Comment by invisiblespider** [comment]
![Artboard 1](https://user-images.githubusercontent.com/62538833/77296798-5cee5080-6cf9-11ea-9fc8-96ced7a38c19.png)
![Artboard 2](https://user-images.githubusercontent.com/62538833/77296802-5eb81400-6cf9-11ea-8e00-c3dbd2d37e22.png)
![Artboard 3](https://user-images.githubusercontent.com/62538833/77296804-5f50aa80-6cf9-11ea-8816-b55774f2e313.png)
a few designs based on the idea of >_  
i thought it would be appropriate to use pink carpet.

**Comment by invisiblespider** [comment]
i realize it a bit wide but it just to put out there some ideas

**Comment by Ghoulboy78** [comment]
![image](https://user-images.githubusercontent.com/53367549/77297553-c2d2dc00-6ce9-11ea-9486-3c04071bd259.png)
just an idea to use vscode logos to make the Sc

**Comment by ImUrX** [comment]
gonna tell you, thanks for the forms of the things but its a good idea to have a limited color palette in this case because it will be repeated multiple times
[this is what colors most icons use (intellisense and debug)](https://github.com/microsoft/vscode-icons) but if you got a good reason for not using that palette please say so :D

@invisiblespider im intrigued on why the pink carpet?

**Comment by ImUrX** [comment]
giving another example of how it would look with various icons 
![example](https://i.imgur.com/qBTDSsW.png)

**Comment by invisiblespider** [comment]
it's an indirect reference to the using pink carpet on carpet mod [Carpet Mod for Minecraft 1.14/1.15 - Complete Guide](https://youtu.be/Lt-ooRGpLz4?t=2737)

**Comment by invisiblespider** [comment]
![sc](https://user-images.githubusercontent.com/62538833/77305698-8f9f4580-6d07-11ea-8942-92e0802a2a5d.png)

**Comment by ImUrX** [comment]
![try](https://i.imgur.com/HBdkoTk.png) i tried to recreate the second one with the third one

**Comment by ImUrX** [comment]
Well will close this at the moment, if anyone has any issues please say so

**Comment by ImUrX** [comment]
So guys, i discovered that this is not possible currently in VSCode microsoft/vscode#14662, but I'm seeing if I can make the PR myself or if something is on the works

**Comment by ImUrX** [comment]
will implement this when i have time
